#load @"Akka.Cluster.Tools.fsx" 
#load @"Akka.DistributedData.fsx" 
#load @"Akka.Persistence.fsx" 
#r "System.Data.DataSetExtensions" 
#r "../../../packages/Akka.Cluster.Sharding/lib/net45/Akka.Cluster.Sharding.dll" 